apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx-deployment
spec:
  selector:
    matchLabels:
      app: demo-nginx
  minReadySeconds: 5
  replicas: 3
  template:
    metadata:
      labels:
        app: demo-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
