apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cloudhomework-cert
spec:
  secretName: cloudhomework-tls
  duration: 2160h
  renewBefore: 360h
  organization:
    - url-shortener
  commonName: fourstring.dev
  isCA: false
  keySize: 384
  keyAlgorithm: ecdsa
  keyEncoding: pkcs1
  usages:
    - server auth
  dnsNames:
    - fourstring.dev
    - '*.fourstring.dev'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer