apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-proxy-deployment
spec:
  selector:
    matchLabels:
      app: kibana-proxy
  minReadySeconds: 5
  replicas: 4
  template:
    metadata:
      labels:
        app: kibana-proxy
    spec:
      containers:
        - name: proxy
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: kibana-proxy-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: kibana-proxy-config
          configMap:
            name: kibana-proxy-cm