# Generated by Django 3.1.3 on 2021-01-07 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudhomework', '0003_auto_20210107_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='answer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_answer_homeworks', to='cloudhomework.media', verbose_name='参考答案'),
        ),
    ]
