apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-webserver-map
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  2048;
        use epoll;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        tcp_nopush         on;
        tcp_nodelay        on;
        keepalive_timeout  65;
        etag off;

        server {
            listen 80;
            root /usr/share/nginx/html;

            location / {
                try_files $uri @index;
            }

            location @index {
                add_header Cache-Control no-cache;
                expires 0;
                try_files /index.html =404;
            }

            location ~.*\.(gif|jpg|jpeg|png|bmp|swf)$
            {
                expires  30d;
            }

            location ~.*\.(js|css)?$
            {
                expires  7d;
            }
        }
    }


