- hosts: masters,workers
  become: true
  tasks:
    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - nfs-common

    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
        state: present

    - name: Install docker and its dependecies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      notify:
        - docker status

    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: enable br_netfilter module
      modprobe:
        name: br_netfilter
        state: present

    - name: load br_netfilter on boot
      copy:
        src: br_netfilter.conf
        dest: /etc/modules-load.d/br_netfilter.conf

    - name: Tuning sysctl
      sysctl:
        name: '{{item}}'
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
      with_items:
        - 'net.ipv4.ip_forward'
        - 'net.bridge.bridge-nf-call-ip6tables'
        - 'net.bridge.bridge-nf-call-iptables'

    - name: Add an apt signing key for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding apt repository for Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list

    - name: Install Kubernetes binaries
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - kubelet
          - kubeadm
          - kubectl

    - name: hold Kubernetes packages
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      with_items:
        - kubelet
        - kubeadm
        - kubectl
  handlers:
    - name: docker status
      service: name=docker state=started